#include <iostream>
using namespace std;
int LinearSearch(int A[], int n, int key)
{
    int i, flag = 0;
    for (i = 0; i < n; i++)
    {
        if (A[i] == key)
        {
            flag = 1;
            return i + 1; // Position of the element in array starts from 1 not 0.
        }
    }
    if (flag == 0)
        return -1;
}
int main()
{
    int A[100000], n, i, key;
    cout << "Enter n: ";
    cin >> n;
    for (i = 0; i < n; i++)
    {
        A[i] = rand();
        cout << A[i] << ","; // printing the random integers  generated by rand().
    }
    cout << "\nEnter key: ";
    cin >> key;
    cout << "Key is at pos: " << LinearSearch(A, n, key) << endl;
    return 0;
}
